// Mirrors backend/src/policies/permissions.js. Frontend checks are UX-only —
// the backend is the source of truth and re-checks every one of these server-side.
export const PERMISSIONS = {
  COMPANY_READ: 'COMPANY_READ',
  COMPANY_UPDATE: 'COMPANY_UPDATE',
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ACTIVATE: 'USER_ACTIVATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_READ: 'PROJECT_READ',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',
  ISSUE_CREATE: 'ISSUE_CREATE',
  ISSUE_READ: 'ISSUE_READ',
  ISSUE_UPDATE: 'ISSUE_UPDATE',
  ISSUE_DELETE: 'ISSUE_DELETE',
};
