const { ROLES } = require('../constants/roles');

const PERMISSIONS = {
  COMPANY_READ: 'COMPANY_READ',
  COMPANY_UPDATE: 'COMPANY_UPDATE',
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ACTIVATE: 'USER_ACTIVATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_READ: 'PROJECT_READ',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',
  ISSUE_CREATE: 'ISSUE_CREATE',
  ISSUE_READ: 'ISSUE_READ',
  ISSUE_UPDATE: 'ISSUE_UPDATE',
  ISSUE_DELETE: 'ISSUE_DELETE',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: ALL_PERMISSIONS,
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.ISSUE_READ,
    PERMISSIONS.ISSUE_CREATE,
    PERMISSIONS.ISSUE_UPDATE,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.ISSUE_READ,
    PERMISSIONS.ISSUE_CREATE,
    PERMISSIONS.ISSUE_UPDATE,
  ],
  [ROLES.SUPPORT]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.ISSUE_READ,
  ],
};

function permissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, permissionsForRole };
